export const ROUTES = {
  home: '/',
  races: '/races',
  trainings: '/trainings',
  bestEfforts: '/best-efforts',
  podiums: '/podiums',
  personalOptionRaceTypes: '/personal-options/race-types',
  personalOptionTeams: '/personal-options/teams',
  personalOptionCircuits: '/personal-options/circuits',
  personalOptionShoes: '/personal-options/shoes',
  profile: '/profile',
  settings: '/settings',
  adminRitmaOverview: '/admin-area/ritma-overview',
  adminUserList: '/admin-area/user-list',
  adminPendingApprovals: '/admin-area/pending-approvals',
  login: '/login',
  adminPendingAccounts: '/admin/account-requests',
} as const
